### 게시글 전체 조회
GET http://localhost:8080/articles

### 게시글 저장
POST http://localhost:8080/article
Content-Type: application/json

{
  "title": "title 1",
  "content": "content 1"
}

### 게시글 단건 조회 - 성공 <-- 게시글 저장 구현 후 사용
GET http://localhost:8080/articles/1

### 게시글 단건 조회 - 없는 게시글 <-- 게시글 저장 구현 후 사용
GET http://localhost:8080/articles/1000


### 게시글 수정
PUT http://localhost:8080/articles/1
Content-Type: application/json

{
  "id": 1,
  "title": "title 11",
  "content": "content 11"
}


### 게시글 여러 건 삭제
DELETE http://localhost:8080/articles
Content-Type: application/json

[1, 2, 3, 4, 5]

### 게시글 1건 삭제
DELETE http://localhost:8080/articles/3
Content-Type: application/json

